### ISSUE TITLE
Term2 does not respect Pane Size

### ISSUE THREAD

**Issue by jcpetkovich** [f/atom-term2#80]
Term2 does not appear to respect pane sizes. I used atom `0.161.0` built from source. This is with the most recently published `Term2` package (`0.9.4`), and I used an empty `.atom` besides this package.

As you can see, when I open a new term, tabs get pushed off the screen:

![tabs-gone](https://cloud.githubusercontent.com/assets/159257/5473688/4b66728c-85d9-11e4-9b3f-ab847a1849f0.png)

And the bottom of the pane gets pushed up:

![bottom-gets-pushed-up](https://cloud.githubusercontent.com/assets/159257/5473691/535a2b78-85d9-11e4-8b55-fbe285b67db0.png)

The terminal lines themselves go way past the barrier of the pane, to the point where I can't see the cursor anymore:

![term-lines-go-way-past-pane](https://cloud.githubusercontent.com/assets/159257/5473757/f45697b4-85d9-11e4-8c2f-98740434da1a.png)

This makes it pretty unusable, and I haven't quite figured out what's wrong.

I have no idea how to go about debugging this.

**Comment by mauricioszabo** [comment]
I'm having this issue too. Even more, when I resize, the terminal size appears right, but commands are pushed past the end of view, this too rendering quite unusable.

**Comment by prescottprue** [comment]
I am getting this as well. It adds a huge white pane to the bottom and makes all of my tabs at the top of the screen cut off. 
It might also be good to have a little more documentation on how to change visual settings (css classes) so that things like this could be played with more. I had to guess and test CSS classes stuff just to up the font sizes.
